Ci tool param
projecttacoma/connectathon pull request #3
Opened 2020-04-03 13:27 UTC by jbradl11

Setting up basic Travis testing of running `make all all-r4 CI_TOOL=true`, using the updated FHIR-Patient-Generator.

2020-04-03 14:28 UTC, okeefm requested changes
Changes make sense to me, given that the `Makefile` can now install FBC on its own. PR needs a rebase/deconfliction before it can get merged.

2020-04-03 19:49 UTC, okeefm commented on travis/test_measures.sh
> +make all all-r4 CI_TOOL=true
Do you actually need both the `all` and `all-r4` targets here? I think they do the same thing in FHIR Patient Generator.

2020-04-09 12:18 UTC, tstrass requested changes

2020-04-09 12:18 UTC, tstrass commented on travis/test_measures.sh
> +git checkout ci-param-tool-rebase
```suggestion
git checkout master
```
Did you mean to change this to `master`? That other branch was merged and deleted.

2020-04-09 12:21 UTC, tstrass commented on travis/test_measures.sh
> +git checkout ci-param-tool-rebase
Oh wait no `checkout master` would be redundant, so I guess did you want to remove this?

2020-04-09 12:45 UTC, okeefm commented on travis/test_measures.sh
> +make all all-r4 CI_TOOL=true
Also I just realized my comment could be confusing-- I believe that `make all` and `make all-r4` are aliases for the same makefile target in FHIR Patient Generator, is what I meant to say.

2020-04-14 13:04 UTC, tstrass approved these changes

2020-04-14 13:27 UTC, okeefm approved these changes
Looks good to me. Thanks for the updates!

2020-04-14 13:29 UTC, merged